name: shape_editor
description: A flutter shape editor library that provides DiagramEditor widget.
version: 0.0.8
homepage: https://github.com/NicolasCiviero/flutter_diagram_editor
repository: https://github.com/NicolasCiviero/flutter_diagram_editor

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  uuid: ^3.0.7
  flutter_colorpicker: ^1.0.3
  event: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
